### PR TITLE
Remove unnecessary temporary variable 'k'

### PR DESCRIPTION
**Pull request by xiaosuo**

### CODE REVIEW

**Comment by ghemawat** [comment]
My guess is that this change is not worth the amount of effort needed to sign the CLA, merge the commit, run the tests, etc..  The old code is clear enough as is.

**Comment by xiaosuo** [comment]
@ghemawat It means that this micro cleanup is so obvious that no tests is needed. :)

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
@xiaosuo I am going to side with sanjay and stick with the current implementation. Thank you for your pull request.

**Pull request closed without merging**
