### PR TITLE
fix typo in port_example.h

### PR DESCRIPTION
**Pull request by JayiceZ**

### CODE REVIEW

**Comment by Jayice-zjw** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by pwnall — APPROVED** [review]
LGTM. Thank you for the fix!

**Comment by pwnall** [comment]
The CLA check failed. This needs to pass in order for us to consider merging this.

**Comment by JayiceZ** [comment]
> The CLA check failed. This needs to pass in order for us to consider merging this.

Resigned CLA just now. PTAL~

**Comment by pwnall** [comment]
Looks great, thank you!

**Pull request merged**
