### PR TITLE
Clean up compile-time warnings (gcc 7.1)

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I think the CLA bot is just broken - I've got the email used in git in my google account and had signed the CLA long ago. I'm not gonna create a new google account with that email just to sign the CLA.

**Comment by MarcoFalke** [comment]
@pwnall This seems to be commonly reported (#558, #459). Any chance at taking a look?

**Comment by pwnall** [comment]
@MarcoFalke Sorry, I should've documented my thoughts.

I looked at this earlier. It definitely looks like a good step forward, but I haven't been able to find the time to test it properly. Specifically, `ConsumeDecimalNumber` in `util/logging.cc` has ran into compiler bugs (or UB?) before, so I'd need to repro the crashiness fixed by 09a3c8e7417547829b94bcdaa62cdf9e896f29a9 and make sure this code change doesn't reintroduce it.

**Comment by pwnall** [comment]
a0008deb679480fd30e845d7e52421af72160c2c took care of `ConsumeDecimalNumber`. The other 2 fixes LGTM. I'll get them through our internal repository.

Thank you for your contribution!

**Comment by pwnall** [comment]
This PR landed as commit 14cce848e7b8a040a8f457d5a796722a55e19597. Thank you for your contribution!

**Pull request closed without merging**
