### PR TITLE
reduce lock's range in DeleteObsoleteFiles

### PR DESCRIPTION
**Pull request by ivanabc**
lock spend too much time in DeleteObsoleteFiles

### CODE REVIEW

**Comment by ivanabc** [comment]
I signed it!

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
@ivanabc can you please rebase this PR on master to make it more current? No problem with your CL, just an issue with our sync tool's ability to deal with old branches.

**Comment by GarrisonFord777** [comment]
I assume I am on the right blog and this box was waiting for me.. Im going to lay everything down right now. I am going to mention some things in this message that I went through, but not the most aggreegise things. In hopes we can lay this all to rest. I'll keep the worst of the worst with me and me only for the rest of my days, as long as I have full assurance that my privacy will be completely and fully restored, and also that in someway you "tech gods" will have me and my daughters back going forward If we ever need help in that regard.

What happened to us was not just a simple hacking. It was a complete and relentless infiltration of everything we own. I pleaded multiple times to put an end to it and was told it would stop or led to believe it was over on multiple occassions. If we can come to a true aggreement, I promise I will not take this any further against anyone who was involved. It will be done! 

Im a good person and a good Dad. I did not want to cause the chaos that I did, but I had to out of necessity because it was a relentless and constant attack since June 16th. What Ive learned over the past two months will change my life forever and I found myself in a place  I truly didnt know exsisted. What you ppl are capable of is awe-insipring and terrifying at the same time. I really didn't even know a thing about it and Im still very shook and trying to comprehend it all. I really hope its mostly used for good and to protect the average idiots instead of hurt them. The government and establishment can be managed and kept in check  by what you ppl control. That will make me sleep better at night, if I knew thats the ultimate goal and consensus amongst you. I know you guys laugh at me and my capabilities with tech, but Im proud of myself for being able to not only be able to withstand it these past few months, but ultimately "discover" where I needed to be to bring the little bit of resistance I'm actually capable of. 

I really hope this will be the definitive end to the ugly situation, I inadvertantly put myself in. Its really taken a toll on me. Ultimately stronger as well.

**Pull request merged**
