### PR TITLE
Add install make target & pkg-config file

### PR DESCRIPTION
**Pull request by njwhite**
Fixes [138](https://code.google.com/p/leveldb/issues/detail?id=138) and [139](https://code.google.com/p/leveldb/issues/detail?id=139).

### CODE REVIEW

**Comment by bok** [comment]
This PR fixes #144 and #145. I have successfully tested the changes in a Debian wheezy environment. 

Can this be merged please?

**Comment by njwhite** [comment]
Ping! Over one year old :(

**Comment by njwhite** [comment]
I signed it!

**Comment by antran89** [comment]
ping! Over another year!

**Comment by njwhite** [comment]
@antran89 oops, the email address I committed as wasn't the one linked to my Github account. All fixed (and rebased, it's been two years)!

CC @cmumford

**Comment by icholy** [comment]
Is there something specific blocking this?

**Comment by kcolford** [comment]
Hey, installing this is really inconvenient without the install target, please accept this pr already.

**Comment by njwhite** [comment]
Ping @pwnall - you've committed quite a lot recently, can you help? Thanks -

**Comment by pwnall** [comment]
We're planning to switch to CMake, at which point the Makefile will be removed.

I'm sorry I haven't had time to complete the migration earlier, and thus caused you to spend time on this PR.

In case you're wondering, the CMake migration is blocked on changes needed to the internal codebase, so we can't get external help on that.

**Comment by njwhite** [comment]
@pwnall thanks for the update! It'd be great if the cmake build generate a pkg-config file - otherwise I'll port this PR over when it's released...

**Comment by MarcoFalke** [comment]
Needs rebase if still relevant, I guess.

**Comment by JaapWijnen** [comment]
Would be awesome if this would be implemented :)

**Comment by pwnall** [comment]
I'm going to close this PR, because it targets the now-removed Make-based build system.

The CMake configuration includes install support -- please try it out and see if it works for you.

**Comment by JaapWijnen** [comment]
Any plans for a pkg-config file though? As I'm having trouble making Swift bindings without it

**Pull request closed without merging**
