### PR TITLE
Implement support for meta blocks

### PR DESCRIPTION
**Pull request by vadimskipin**
This is proposal for feature that allows users to store arbitrary meta blocks (stats or something) inside sstables:
- Low-level API includes TableBuilder::AddMetaBlock and Table::ReadMeta along with Table::NewMetaIterator.
- Mid-level API includes Version::VisitMeta that accepts visitor to visit all meta data blocks defined for this version. It also provides simple range-filter to visit only subset of sstables.
- High-level API not provided.

### CODE REVIEW

**Comment by pablopitta** [comment]
|I signed it!|

Il 30/09/2015 21:52, googlebot ha scritto:

**Comment by vadimskipin** [comment]
I signed it!

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
Thanks for the PR @vadimskipin. We strive to keep the API as lean and simple as possible. I think the user can accomplish the same thing by partitioning the keyspace or possibly with a custom comparator.

**Pull request closed without merging**
