### PR TITLE
add travis support

### PR DESCRIPTION
**Pull request by Liuchang0812**
travis-ci will run "make check" for any PR and change of leveldb project. I think it's will useful

### CODE REVIEW

**Comment by cmumford** [comment]
Hi @Liuchang0812 I was looking into adding Travis CI and saw your pull request. I'd prefer to give you the credit, but before I can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

**Comment by ralphtheninja** [comment]
+1

**Comment by cmumford** [comment]
Hi @Liuchang0812:

I didn't hear back from you before needing to add support for Travis-CI myself. It was merged in 43fcf23.

**Comment by Liuchang0812** [comment]
@cmumford sorry for this too later replay, i have signed it。

**Pull request closed without merging**
