### PR TITLE
Automatically fallback to regular file IO if mmap fails.

### PR DESCRIPTION
**Pull request by jcoffland**
This change allows LevelDB to continue operating when virtual memory is exhausted.

Despite LevelDB's use of `MmapLimiter`, which hard codes the maximum number of open mmaps to 1000 for 64-bit systems, LevelDB can still run out of virtual memory for mmaps.  Rather than fail, this PR allows LevelDB to automatically fallback to regular file IO when  `mmap()` fails.  LevelDB already does this anyway when 1000 mmaps are reached.

With this change it I've also removed `MmapLimiter`, which is no longer necessary.  This has the following additional benefits:
- Improves performance by eliminating mutex locks in `MmapLimiter::Acquire()` and `MmapLimiter::Release()`.
- Makes mmaps possible on 32-bit systems. (`MmapLimiter` disallowed this.)
- Potentially allows 64-bit systems to use more mmaps when virtual memory is available.
- Simplifies the code and removes a hard coded limit.

I believe this is a low risk change.  The main logic changes are limited to the function `NewRandomAccessFile()` and removal of `class MmapLimiter` only affects `class PosixMmapReadableFile` and `NewRandomAccessFile()`.  Both of these changes are limited to the file `env_posix.cc`.  No function or class signatures which are accessed outside of `env_posix.cc` have been changed.

### CODE REVIEW

**Comment by jcoffland** [comment]
I signed it!

**Comment by jcoffland** [comment]
Any chance this will get looked at?  This is a fix for an important bug.  leveldb crashes when you run out virtual memory otherwise.

**Comment by jcoffland** [comment]
Anyone there?  Could really use some help with this.

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
Thx for the PR @jcoffland. One advantage of using MmapLimiter (not just called Limiter) is that it allows the tests to exercise both the mmap and regular I/O paths. Can you preserve this?

**Comment by jcoffland** [comment]
@cmumford  Nope.

**Comment by jcoffland** [comment]
The handling of this PR is really disappointing.  After 3 years of being ignored, I get a request to do more work.  I declined because there's no guarantee my work won't be ignored again.  This PR fixes an important bug in LevelDB and should have been merged a long time ago.

**Comment by pwnall** [comment]
@jcoffland I'm sorry you feel this way.

Regarding timing -- We're focusing on what we expect to make the biggest improvements for the use cases in which we're deploying LevelDB.

Regarding testing -- We're running LevelDB on billions of devices, via Chrome. Correctness is really important to us, and adequate test coverage is not negotiable.

**Comment by yujiapingyu** [comment]
Why I can't get the Value of a exsit Key when I set  maximum number of open mmaps to 0 ？

**Pull request closed without merging**
