### PR TITLE
Native windows port #519 (mingw 32/64 + msvc 2015/2017)

### PR DESCRIPTION
**Pull request by olegator77**
Hi 

Here is CMake based native windows port of leveldb's master.

### CODE REVIEW

**Comment by mattn** [comment]
I could build this on Windows with mingw compiler. Thank you.

**Comment by SpaceView** [comment]
very nice, !build successfully with vs2017

**Comment by danielgindi** [comment]
@ghemawat Any intention to merge this?

**Comment by pwnall** [comment]
@danielgindi We have an internal version in review, but haven't had the time to drive it across the finish line. I'm keeping the Windows PRs open to make it easy for us to attribute credit to all folks who submitted drafts.

Commenting in the PRs and issues is OK if you want to coordinate with other contributors interested in the same topic. Asking for updates from us won't change the prioritization of your issues, and will only create noise -- we don't have any timelines to share for work in this repository, so all I will ever be able to say is "we're working on this, you'll see it when it's ready".

Please don't ping specific people. The maintainers are watching all the issues, and will respond when appropriate.

**Comment by danielgindi** [comment]
Thanks. I did not intend to create noise, or even get an accurate ETA. Knowing that this is still in review and there's an intention to merge/implement in some way - that's comforting enough, for now.

**Comment by pwnall** [comment]
We've landed the official Windows support, based on code from Chrome. Going to close this PR now. Sorry we couldn't get to it sooner!

**Pull request closed without merging**
