### PR TITLE
Add argument definition for void c functions.

### PR DESCRIPTION
**Pull request by allangj**
Allow the use c.h on projects with -Wstrict-prototypes flag

### CODE REVIEW

**Comment by cmumford** [comment]
Hi allangj:

Thanks for the pull request. Can you also modify Makefile and add -Wstrict-prototypes to CFLAGS to prevent future regressions?

**Comment by allangj** [comment]
Hi,
I modified the build_detect_platform instead as in the makefile I didn’t see a were to add them in a clean way.
I add the flag for the Cygwin, Linux and IOS as I was able to verify its correctness for those OS. 
Also add the -Werror flag in order to trigger the error in case of future regressions.

Is you prefer to add it to the makefile please tell me and I will do the change, also if any other suggestions I will be happy to do it.

Thanks

**Comment by allangj** [comment]
@cmumford is anything more necessary in this request? thanks

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
Hi @allangj: Sorry for the very long delay, but we're finally processing our backlog. If you wish to resolve the conflicts I will do the merge asap. The include/leveldb/c.h conflicts should be fairly straightforward to resolve, and the only thing you need to do to add `-Wstrict-prototypes` to the build is to add the following one line change to `CMakeLists.txt`:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1409c06..da54112 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -50,6 +50,8 @@ check_cxx_symbol_exists(F_FULLFSYNC "fcntl.h" HAVE_FULLFSYNC)
 
 include(CheckCXXSourceCompiles)
 
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wstrict-prototypes")
+
 # Test whether -Wthread-safety is available. See
 # https://clang.llvm.org/docs/ThreadSafetyAnalysis.html
 # -Werror is necessary because unknown attributes only generate warnings.
```

**Comment by allangj** [comment]
@cmumford changes applied

**Pull request merged**
