### PR TITLE
Call rep_->file->Sync() at the end of TableBuilder::Finish()

### PR DESCRIPTION
**Pull request by rocks**
When I used TableBuilder to manually build an SSTable, I found that TableBuilder::FileSize() was not equal to the size of rep_->file after I called TableBuilder::Finish(). It was very confusing to me.

The reason is that TableBuilder::Finish() does not call rep_->file->Sync() at the end. So, some data(meta index block, index block, and footer block ) in rep_->file may be still buffered and not flushed to persistent storage.

**But semantically, "Finish" means that after we called this function successfully, the SSTable should be completely built.**

So, I think that rep_->file->Sync() should be called at the end of TableBuilder::Finish().

[https://github.com/google/leveldb/blob/master/table/table_builder.cc#L240](https://github.com/google/leveldb/blob/master/table/table_builder.cc#L240)
```cpp
  // Write footer
  if (ok()) {
    Footer footer;
    footer.set_metaindex_handle(metaindex_block_handle);
    footer.set_index_handle(index_block_handle);
    std::string footer_encoding;
    footer.EncodeTo(&footer_encoding);
    r->status = r->file->Append(footer_encoding);
    if (r->status.ok()) {
      r->offset += footer_encoding.size();
    }
  }

  if (ok()) {
    r->status = r->file->Sync();
  }
  return r->status;
```

### CODE REVIEW

**Comment by npatod** [comment]
there is already a file flush function getting called.(TableBuilder::Finish() -> TableBuilder:Flush() 
TableBuilder:Flush() writes data_block data and then call  r->file->Flush().
now in this pull request we writes (meta index block, index block, and footer block ) then again calling 
r->file->Flush().
I just want to know can we call TableBuilder:Flush()  at the end instead of begging of TableBuilder::Finish()  .

**Comment by rockley** [comment]
> there is already a file flush function getting called.(TableBuilder::Finish() -> TableBuilder:Flush()
> TableBuilder:Flush() writes data_block data and then call r->file->Flush().
> now in this pull request we writes (meta index block, index block, and footer block ) then again calling
> r->file->Flush().
> I just want to know can we call TableBuilder:Flush() at the end instead of begging of TableBuilder::Finish() .

Sorry, I don't quite understand what you mean. But what TableBuilder:Flush() does is that write **data block** and flush it. This issue concerns that after the TableBuilder:Finish() is called successfully, there may some data (filter block, etc.) are still buffered. This may cause that the SSTable on persistent storage is incomplete.

I noticed that file->flush() is called out of TableBuilder:Finish(). But I think call file->flush() in TableBuilder::Flush() is better than out of it (to avoid forget to call flush()).

**Comment by npatod** [comment]
Thanks Rockley,
As I know, when we call flush on a file handler then internally it calls fsynch which flush all data from os buffer(memory) to a persistent store (hard disk). Please correct me if I am wrong.
If I am right then we are executing 2 times flush operation on a file handler one inside TableBuilder:Flush() after writing block data and again one more time after writing filter block data.
I have below question now
1)when we call flush on a file handler then it flush all data or some selected data (like data  block, index block.)
2)is it possible to use only one flush operation and we will get the desired result?
3)if it possible then is there any performance gain?

**Comment by rockley** [comment]
> Thanks Rockley,
> As I know, when we call flush on a file handler then internally it calls fsynch which flush all data of a file from os buffer(memory) to a persistent store (hard disk). Please correct me if I am wrong.
> If I am right then we are executing 2 times flush operation on a file handler one inside TableBuilder:Flush() after writing block data and again one more time after writing filter block data.
> I have below question now
> 1)when we call flush on a file handler then it flush all data or some selected data (like data block, index block.)
> 2)is it possible to use only one flush operation and we will get the desired result?
> 3)if it possible then is there any performance gain?

From my perspective, the calls of TableBuilder::Flush() are used to completes the build of the data block and reset block builder (to reduce memory usage, otherwise the whole SSTable needs to be buffered in memory. I think this is the main reason to call Flush()).

The TableBuilder::Flush() at the begin of TableBuilder::Finish() is called to finish the last data block. Indeed, the rep_->file->Flush() in TableBuilder::Flush() here can be avoided. But for simplicity, directly use the TableBuilder::Flush() here seems to be understandable.

Additionally, because we call rep_->file->Sync() in TableBuilder::Finish(), I remove thoses redundant file->Sync() out of TableBuilder::Finish(). You can see `Files Changed`. :)

For your questions:
1. We call file->Flush() when every data block is finished.
2. Yes, we can use only one file->Flush() **at the cost of more memory usage**.
3. Of course, less file->Flush() results in a performance gain.

**Comment by siying** [comment]
What's the benefit of calling sync inside TableBuilder::Finish() than in flush or compaction? I can think of one downside: TableBuilder is pluggable, so if we don't do fsync in flush and compaction, every table builder implementation needs to do it. For example, the current pull request doesn't do the same for PlainTable and CuckooTable.

**Pull request closed without merging**
