### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by falvojr**
Update a broken link for Snappy.

### CODE REVIEW

**Comment by cmumford** [comment]
Hi falvojr:

Thx for this pull request. I'd like to merge your request, but you need to sign the CLA. Follow the instructions above. Also, more info at https://github.com/google/leveldb#submitting-a-pull-request (like rebase on master). If I don't hear from you after a while I'll make this change myself as this has been on my list to fix as well.

thx.

**Comment by falvojr** [comment]
Thank you @cmumford, done!

**Comment by ralphtheninja** [comment]
:+1:

**Comment by cmumford** [comment]
Thx falvojr:

Can I get you to rebase on google/leveldb/master? See if these instructions make sense:

    git remote add google https://github.com/google/leveldb.git
    git fetch google
    git checkout patch-1
    git rebase google/master
    git push -f origin

**Pull request merged**
