### PR TITLE
replace std::uint64_t -> uint64_t

### PR DESCRIPTION
**Pull request by proller**
https://github.com/google/leveldb/issues/340
fix android build

### CODE REVIEW

**Comment by proller** [comment]
wat ?
just remove two std:: without my agreement, credit card number, and other urinalysis

**Comment by MoNTE48** [comment]
@proller It automatically checks and it required. Haha

**Comment by cmumford** [comment]
haha - yeah, that's way Google rolls - sorry. If you don't want to sign the CLA, and that's totally cool, just file a bug and I'll get around to doing that eventually.

**Comment by cmumford** [comment]
Addressed in pull request nw362#354.

**Pull request closed without merging**
