### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
I signed it!

**Comment by dimitris-t** [comment]
I signed it!

**Comment by MarcoFalke** [comment]
I signed it!

**Comment by dimitris-t** [comment]
As the commit author I approve of this pull request.

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
Thanks for the PR @MarcoFalke. I didn't notice this earlier and this typo was just recently fixed in https://github.com/google/leveldb/commit/71ed7c401ec1b1e38d6f7cb9eb2fcff93c24d1f1.

**Pull request closed without merging**
