### PR TITLE
Link to style guide is broken

### PR DESCRIPTION
**Pull request by nayafia**
I'm pretty sure I found the updated link, which I've fixed here, but lmk if incorrect!

### CODE REVIEW

**Comment by nayafia** [comment]
Signed the CLA!

**Comment by zackurben** [comment]
Can we get this merged in? I was about to submit a duplicate pr 😂  

cc @googlebot

**Comment by cmumford** [comment]
@googlebot rescan

**Comment by cmumford** [comment]
Thx for the PR @nayafia and sorry I missed this. The link was corrected in b5d4a22e.

**Pull request closed without merging**
