### PR TITLE
LevelDB on Windows

### PR DESCRIPTION
**Pull request by topilski**
Hi, i used MSYS2 and mingw compiler , if this pull request interesting for you please merge if not simple reject. I tested code on Windows/Linux/MacOSX , used in FastoNoSQL application.

### CODE REVIEW

**Comment by topilski** [comment]
I signed it!

**Comment by jdrago999** [comment]
Hey - can we get a hand with this last and final step?

**Comment by topilski** [comment]
Hi @jdrago999 , yes you can.

**Comment by dongguaWDY** [comment]
does level db support windows?

**Comment by topilski** [comment]
Hi @dongguaWDY , no , it is unoffical changes. For example here: https://github.com/fastogt/leveldb we use it in FastoNoSQL.

**Comment by pwnall** [comment]
We've landed the official Windows support, based on code from Chrome. Going to close this PR now. Sorry we couldn't get to it sooner!

**Comment by topilski** [comment]
Hi @pwnall it is good news, when windows version will be merge into master?

**Comment by pwnall** [comment]
It's on top of master. The current code is failing some tests, and a fix is under review in our internal repository.

**Comment by topilski** [comment]
ok, i will check, thank you!

**Comment by pwnall** [comment]
The code on master now passes all tests on Windows! Thanks everyone for your patience!

**Pull request closed without merging**
