### PR TITLE
Add support for many Debian architectures.

### PR DESCRIPTION
**Pull request by alessio**
Author: Nobuhiro Iwamatsu iwamatsu@debian.org

### CODE REVIEW

**Comment by alessio** [comment]
I signed it some years ago.

Cheers.

On Thu, May 7, 2015 at 9:23 AM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project, in which case you'll need to
> sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/leveldb/pull/291#issuecomment-99768799>.
>



-- 
Alessio Treglia          | www.alessiotreglia.com
Debian Developer         |     alessio@debian.org
Ubuntu Core Developer    |  quadrispro@ubuntu.com
0416 0004 A827 6E40 BB98 90FB E8A4 8AE5 311D 765A

**Comment by smithfarm** [comment]
@alessio rebase?

**Comment by smithfarm** [comment]
@alessio Apparently, there is some robot that does something if you post a comment saying "I signed it!"

Is that right, @cmumford ?

**Comment by smithfarm** [comment]
Getting this merged ASAP would help distro maintainers. Thanks!

**Comment by pwnall** [comment]
The current code uses C++11 atomics, so this PR is no longer needed. LevelDB should now build with any compiler that has good C++11 and POSIX support.

**Pull request closed without merging**
